-- COPIA Y PEGA ESTO EN EL "SQL EDITOR" DE SUPABASE Y DALE A "RUN"

-- 1. Tabla de Configuración (para saber si la votación está abierta o cerrada)
CREATE TABLE IF NOT EXISTS config (
    key TEXT PRIMARY KEY,
    value JSONB
);

INSERT INTO config (key, value) VALUES ('voting_open', 'true') ON CONFLICT DO NOTHING;

-- 2. Tabla de Opciones (las cosas a votar)
CREATE TABLE IF NOT EXISTS options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertamos algunas opciones de ejemplo
INSERT INTO options (name) VALUES 
    ('Opción A'), 
    ('Opción B'), 
    ('Opción C'), 
    ('Opción D'), 
    ('Opción E');

-- 3. Tabla de Votos
CREATE TABLE IF NOT EXISTS votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_name TEXT NOT NULL,
    option_id BIGINT REFERENCES options(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Habilitar Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE votes;
ALTER PUBLICATION supabase_realtime ADD TABLE config;
ALTER PUBLICATION supabase_realtime ADD TABLE options;

-- 5. Políticas de Seguridad (Ruls) - Muy permisivas para este prototipo rápido
ALTER TABLE config ENABLE ROW LEVEL SECURITY;
ALTER TABLE options ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

-- Permitir a todo el mundo leer y escribir (simplificado para este uso)
CREATE POLICY "Public Access Config" ON config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Options" ON options FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Votes" ON votes FOR ALL USING (true) WITH CHECK (true);
